from enum import Enum


class MessageCode(Enum):
    SIGN_UP = 1
    SIGN_IN = 2
    JOIN_RANKED_QUEUE = 3
    JOINED_RANKED_ROOM = 4
    CANCEL_JOINING_RANKED = 5
    CREATE_PRIVATE_ROOM = 6
    JOIN_PRIVATE_ROOM = 7
    LEAVE_PRIVATE_ROOM = 8
    KICK_FROM_PRIVATE_ROOM = 9
    START_PRIVATE_GAME = 10
    GAME_SURRENDER = 11
    GAME_OFFER_DRAW = 12
    GAME_RESPOND_TO_DRAW_OFFER = 13
    GAME_CLAIM_DRAW = 14
    GAME_MOVE = 15
    GAME_TIME_END = 16
    PLAYER_DISCONNECTED = 17
