from enum import Enum


class MessageCode(Enum):
    SIGN_UP = 1
    SIGN_IN = 2
    JOIN_RANKED_QUEUE = 3
    JOINED_RANKED_ROOM = 4
    CANCEL_JOINING_RANKED = 5
    CREATE_PRIVATE_ROOM = 6
    JOIN_PRIVATE_ROOM = 7
    GUEST_JOINED_PRIVATE_ROOM = 8
    LEAVE_PRIVATE_ROOM = 9
    KICK_FROM_PRIVATE_ROOM = 10
    START_PRIVATE_GAME = 11
    GAME_SURRENDER = 12
    GAME_OFFER_DRAW = 13
    GAME_RESPOND_TO_DRAW_OFFER = 14
    GAME_CLAIM_DRAW = 15
    GAME_MOVE = 16
    GAME_TIME_END = 17
    PLAYER_DISCONNECTED = 18
